name: "CI Tests"

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: "0 10 * * *"

jobs:
  build:
    name: Build

    env:
      NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
      NGROK_HTTP_EDGE: ${{ secrets.NGROK_HTTP_EDGE }}
      NGROK_TCP_EDGE: ${{ secrets.NGROK_TCP_EDGE }}
      NGROK_API_KEY: ${{ secrets.NGROK_API_KEY }}
      NGROK_HTTP_EDGE_ENDPOINT: ${{ secrets.NGROK_HTTP_EDGE_ENDPOINT }}
      NGROK_TCP_EDGE_ENDPOINT: ${{ secrets.NGROK_TCP_EDGE_ENDPOINT }}

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java-version: [ 11 ]
        include:
          - java-version: 15
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: adopt
      - name: Install dependencies
        run: make install
      - name: Run tests
        run: make test
      - name: Upload coverage
        if: matrix.os == 'ubuntu-latest' && matrix.java-version == '11'
        uses: codecov/codecov-action@v1
        with:
          file: ./build/reports/jacoco/report.xml
