name: "CD"

on:
  release:
    types: [ created ]

jobs:
  deploy:
    name: Deploy

    env:
      NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
      NGROK_HTTP_EDGE: ${{ secrets.NGROK_HTTP_EDGE }}
      NGROK_TCP_EDGE: ${{ secrets.NGROK_TCP_EDGE }}
      NGROK_API_KEY: ${{ secrets.NGROK_API_KEY }}
      NGROK_HTTP_EDGE_ENDPOINT: ${{ secrets.NGROK_HTTP_EDGE_ENDPOINT }}
      NGROK_TCP_EDGE_ENDPOINT: ${{ secrets.NGROK_TCP_EDGE_ENDPOINT }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Install dependencies
        run:
          make install
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Validate version
        run:
          make validate-release VERSION=${{ steps.get_version.outputs.VERSION }}
      - name: Run tests
        run:
          make test
      - name: Build
        run: |
          make docs
          make local
      - name: Publish
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run:
          make upload
