name: Release

run-name: Release ${{ github.ref_name }}

on:
  release:
    types: [ created ]

permissions:
  contents: write
  issues: none
  pull-requests: none

jobs:
  validate-version:
    name: Validate Version

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: zulu
      - name: Validate version
        run: make validate-release VERSION=${GITHUB_REF#refs/tags/}

  build:
    name: Build
    uses: alexdlaird/java-ngrok/.github/workflows/build.yml@main
    secrets: inherit

  release:
    name: Release
    needs: [build, validate-version]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: zulu
      - name: Publish
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
        run: make upload
